# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cpu_xdc.xdc

# IP: ip/programrom/programrom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programrom || ORIG_REF_NAME==programrom} -quiet] -quiet
